/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.abin.lee.thrift.rpc.enums;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum BusinessRoleEnum implements TEnum {
  SUPER(0),
  SYSTEM(1),
  MANUAL(2),
  ADMIN(3),
  DEFAULT(4);

  private final int value;

  private BusinessRoleEnum(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static BusinessRoleEnum findByValue(int value) { 
    switch (value) {
      case 0:
        return SUPER;
      case 1:
        return SYSTEM;
      case 2:
        return MANUAL;
      case 3:
        return ADMIN;
      case 4:
        return DEFAULT;
      default:
        return null;
    }
  }
}
